### ISSUE TITLE
Constraint depending on state value

### ISSUE THREAD

**Issue by rodripor** [odow/SDDP.jl#126]
Hello,

I could not find a way to load restrictions to the SDDP model framework depending on the value of a state variable. Particularly in a hydroplant model it is necessary that the spillage variable is zero when the state variable representing the volume of the reservoir is less than a certain value. if i put the condition inside `@constraints` tag i get an error. 
Maybe someone had the same issue and can help me. I would really appreciate that.

Thanks,
Rodrigo Porteiro

**Comment by odow** [comment]
Hi @rodripor,

The two main conditions required by SDDP are
- all state and control variables are continuous
- the cost-to-go function is convex w.r.t. the state variables.

> the spillage variable is zero when the state variable representing the volume of the reservoir is less than a certain value

This sounds dangerous since, if I understand correctly, it requires binary variables to implement. I do have a plan to implement these at some point (see https://github.com/odow/SDDP.jl/issues/100), but it won't be in the near-term.

If you do not include the constraint, do you observe that it is violated when you simulate the policy? Or is this just a constraint you believe should be in the model. I would be surprised if the reservoir spilled when the volume was low.

Oscar

**Comment by odow** [comment]
> In some cases the optimal policy consists in spilling (when turbinate is at maximum) in the upper hydroplant with the only purpose of turbine that water downstream despite being reservoir volume low.

If you have the correct cost on spillage, this suggests that either it is an optimal decision, or the policy has not converged.

This could also be a finite horizon issue where the terminal value of water in the upper reservoir is too low, so the policy spills it to the lower reservoir in order to turbine the water before the end of the time-horizon.

**Comment by odow** [comment]
Closing since this isn't an issue with the library, and the underlying issue (non-convexity) should be discussed in #65.

**Comment by odow** [comment]
See #126 which implements a continuous relaxation approach.
