### ISSUE TITLE
Minor problem with graphing

### ISSUE THREAD

**Issue by aferragu** [odow/SDDP.jl#145]
I'm using your (great so far!) library and following your tutorials. I would like to report a minor issue: when graphing the value functions, the generated file using plotly is a temp file with no html extension (at least on Linux). Hence the browser window pops up but it does not parse the html output.

I tracked the issue to `launch_file` in `visualize.jl` where you do:
`launch_file(html_string, assets, outputfile=replace(tempname(), ".tmp", ".html"))` 

However tempname() does not return an extension .tmp, so nothing gets replaced. It should be:
`launch_file(html_string, assets, outputfile=tempname() * ".html")`

Thanks!
Andrés

**Comment by odow** [comment]
Im away from my computer at the moment, but a quick google suggests: 
https://github.com/JuliaLang/julia/issues/9053#issuecomment-321830152

Pull requests accepted :) I only have a windows machine to test, and Travis doesn't let me open a browser window, but the function could be refactored to test that the html file is created. 

If you have a look, you can also pass your own filename instead of a temporary one.

**Comment by odow** [comment]
> I'm using your (great so far!) library and following your tutorials

Thanks! The tutorials are very much a recent work in progress. They are probably riddled with spelling mistakes etc. If anything isn't clear, let me know because I tend to forget which parts are obvious to me :)
