### ISSUE TITLE
Noise selection in backward pass to reduce amount of subproblems

### ISSUE THREAD

**Issue by rodripor** [odow/SDDP.jl#177]
Hi, i'm trying to reduce the amount of subproblems generated to reduce execution time.
Is there some way to sample only certain subset of noises in the backward pass instead of being exhaustive  to avoid that the framework build a different problem for each noise?. I can't find a way to do it without modifying the package. 

Thanks!

**Comment by odow** [comment]
Unfortunately, no. You will need to modify:

https://github.com/odow/SDDP.jl/blob/d90faae19c90f1fa03636ebe1cee92b083c355c2/src/defaultvaluefunction.jl#L144-L154

the easiest way is probably to implement a function in the SDDP.jl codebase:
```julia
function backward_pass_sampler(subproblem)
    ex = ext(subproblem)
    return 1:length(ex.noiseprobability)
end
```
Then modify the `solvesubproblem!` method so that it is
```julia
for i in backward_pass_sampler(sp)
            setnoise!(sp, ex.noises[i])
            JuMPsolve(BackwardPass, m, sp)
            push!(m.storage.objective, getobjectivevalue(sp))
            push!(m.storage.noise, i)
            push!(m.storage.probability, incoming_probability * ex.noiseprobability[i])
            push!(m.storage.modifiedprobability, incoming_probability * ex.noiseprobability[i])
            push!(m.storage.markov, ex.markovstate)
            push!(m.storage.duals, zeros(nstates(sp)))
            saveduals!(m.storage.duals[end], sp)
end
# Need to re-normalize the probabilities since we're not sampling everything
m.storage.probability ./= sum(m.storage_probability)
m.storage.modifiedprobability./= sum(m.modifiedprobability)
```

Then in your code, overwrite this method with the following
```julia
function SDDP.backward_pass_sampler(subproblem)
    ex = ext(subproblem)
    num_noise = length(ex.noiseprobabilities)
    # Only sample 10% of scenarios.
    return rand(1:N, round(0.1 * N))
end
```

Notes:
- you can sub-sample on the backward pass if the noise is **only** in the right-hand side. It won't work if you have the noise in the objective function or in the constraint coefficients.
- you're sampler has to be random. It can't repeatedly choose the same samples

**Comment by roporte** [comment]
Hi,

I've been working on this but using Julia 0.6 with old SDDP version (pre Kokako), ive noticed that results obtained in the examples ive tested were very good and execution time decreased a lot. Ive migrated all examples to Julia 1.1 and last SDDP. Now i want to modify SDDP package locally, and use modified version to include the flexibility explained in this issue like ive done with Julia 0.6. But package management have changed a lot and i cant find the way to do it. I would like to link my examples with a local copy of SDDP and develop this functionality in it and eventually do a pull request so you can decide if you incorporate it to master branch. 
Can you suggest me the way to carry out this with Julia 1.0 or  maybe give me some link to documentation that allows me to do it?

Thank you!

**Comment by odow** [comment]
Great! I'm very keen to integrate this into the package. It would be a fantastic contribution.

Steps:

1) run `] dev https://github.com/odow/SDDP.jl`. (This will clone the package to `~/.julia/dev/SDDP`.)

2) make changes locally in `~/.julia/dev/SDDP`. (Don't worry about making everything perfect. Just get something that works so we can make a pull request.)

3) If you know how to make a pull request, do so. Otherwise...
   -  Download git
   - `cd` to the `~/.Julia/dev/SDDP` directory
   - run `git checkout -b rp/backward`
   - go to `https://github.com/odow/SDDP.jl` and click `fork` in the top-right
   - run `git remote add --push roporte https://github.com/roporte/SDDP.jl
   - run `git add .`
   - run `git commit`, then edit the commit message that pops up to say something descriptive
   - run `git push -u roporte rp/backward`
   - go to `https://github.com/roporte/SDDP.jl` and follow the instructions to make a pull request

4) once you've made your pull request, we can iterate on the design and make sure it is tested etc. 

Please let me know if you need any help with any of these steps!

**Comment by rodripor** [comment]
Great!, only one more thing. When cloning in dev folder, how can i be sure
my examples are using dev SDDP version? And how can i do while testing my
examples to switch beetween original SDDP package and the package im
changing in dev?, have to make a branch in dev SDDP or can i switch base
folder from dev to packages?

Thank you!

**Comment by odow** [comment]
You can see which packages you are using with `julia> ] st`
<img width="574" alt="image" src="https://user-images.githubusercontent.com/8177701/56870112-0042c280-69d0-11e9-9214-a1f502e248c6.png">
Here, I'm using SDDP in the `/dev` folder, the `master` branch of `MathOptFormat`, and `v0.6.0` of `Gurobi`.

If you make changes to `dev/SDDP`, then when you reload Julia (or use Revise.jl), you will be using the updated changes. 

If you want to get back to the latest SDDP master, you can either use `git checkout master`, `git pull` in the `dev/SDDP` folder, or you can run `julia> ] add https://github.com/odow/SDDP.jl#master`

**Comment by rodripor** [comment]
Hi!

You suggested me to do this in the old SDDP version:

```
for i in backward_pass_sampler(sp)
            setnoise!(sp, ex.noises[i])
            JuMPsolve(BackwardPass, m, sp)
            push!(m.storage.objective, getobjectivevalue(sp))
            push!(m.storage.noise, i)
            push!(m.storage.probability, incoming_probability * ex.noiseprobability[i])
            push!(m.storage.modifiedprobability, incoming_probability * ex.noiseprobability[i])
            push!(m.storage.markov, ex.markovstate)
            push!(m.storage.duals, zeros(nstates(sp)))
            saveduals!(m.storage.duals[end], sp)
end
# Need to re-normalize the probabilities since we're not sampling everything
m.storage.probability ./= sum(m.storage_probability)
m.storage.modifiedprobability./= sum(m.modifiedprobability)

```
Now i am working in the new version and all is quite different, so i changed algorithms.jl:

 ```
 for child in node.children
            child_node = model[child.term]
            **for noise in backward_pass_sampler(child_node)**
                # There are multiple ways to check this. Here is one. Another
                # could be that |objective_state| = |scenario_path|.
                if child_node.objective_state !== nothing
                    update_objective_state(child_node.objective_state,
                        objective_states[index], noise.term)
                end
                TimerOutputs.@timeit SDDP_TIMER "solve_subproblem" begin
                    (new_outgoing_state, duals, stage_objective, obj) =
                        solve_subproblem(
                            model, child_node, outgoing_state, noise.term
                        )
                end
                push!(dual_variables, duals)
                push!(noise_supports, noise)
                push!(child_indices, child_node.index)
                push!(original_probability,
                    child.probability * noise.probability)
                push!(objective_realizations, obj)
            end
            **original_probability ./= sum(original_probability)**
  end
```

and add the function:

```
function backward_pass_sampler(node)
    return node.noise_terms
end

```
but i cant figure out if i have to to something equivalent to the old suggestion: 

`m.storage.modifiedprobability./= sum(m.modifiedprobability)`

I think that it isnt necessary because probability distribution tranformations are treated in a different way, but im not sure. Am i right?

When i tested deeply in some examples ill do the pull request.
Thank you!

**Comment by odow** [comment]
Please make a pull request, even in a half-finished state. It is easier to comment an iterate.

There is one nasty problem with this approach, namely that `sum(original_probability)` might not equal `1`, for example, if there are cycles (infinite horizon) in the graph.

You might need something like
```Julia
abstract type AbstractBackwardPassSampler end
struct CompleteSampler <: AbstractBackwardPassSampler end
sample_backward_noise_terms(::CompleteSampler, node) = node.noise_terms

backward_sampler = CompleteSampler()

for child in node.children
           child_node = model[child.term]
           for noise in sample_backward_noise_terms(backward_sampler, child_node)
               # There are multiple ways to check this. Here is one. Another
               # could be that |objective_state| = |scenario_path|.
               if child_node.objective_state !== nothing
                   update_objective_state(child_node.objective_state,
                       objective_states[index], noise.term)
               end
               TimerOutputs.@timeit SDDP_TIMER "solve_subproblem" begin
                   (new_outgoing_state, duals, stage_objective, obj) =
                       solve_subproblem(
                           model, child_node, outgoing_state, noise.term
                       )
               end
               push!(dual_variables, duals)
               push!(noise_supports, noise)
               push!(child_indices, child_node.index)
               push!(original_probability,
                   child.probability * noise.probability)
               push!(objective_realizations, obj)
           end
 end

if !isa(backward_sampler, CompleteSampler)
    denominator = 0.0
    for child in node.children
        for noise in model[child.term].noise_terms
            denominator += noise.probability
        end
    end
    original_probability .*= (denominator / sum(original_probability))
end
```

**Comment by aferragu** [comment]
Let me pitch in here to clarify some things and @odow you may evaluate if this is feasible: I don't think is as easy as renormalizing the probabilities.

What @rodripor proposed is, in order to reduce the number of subproblems, to sample some of the noises _following the noise.probability_ and then in the rest of the algorthm (where the cut coefficients are calculated) average the coefficients by `1/number_of_samples`, i.e. a MonteCarlo algorithm to evaluate the expected value of the cut coefficients over the noise.

Therefore, the sampler should sample following the `noise.probability`, and the modified SDDP algorithm should weigh the noise realizations by `child.probability * 1/number_of_samples`.

Sampling (in any way) and then renormalizing probabilities I think is wrong (except in the trivial case where the noise is uniformly distributed).

When we discussed this with @rodripor we were thinking about the Expectation risk measures. I think all of the above holds also if you sample with the properly modified probabilities calculated for the risk measure, but I'm not as familiar with SDDP for the other risk measures.

The problem with this is that I don't think it can be done as proposed earlier, unless you add a "weight" to each noise sample, such that the weight equals the original probability when using `CompleteSampler` and `1/number_of_samples` when using Montecarlo, and then SDDP uses this weight in the cut coefficient computations.

**Comment by odow** [comment]
> to sample some of the noises following the noise.probability and then in the rest of the algorthm (where the cut coefficients are calculated) average the coefficients by 1/number_of_samples

I understand @rodripor's proposal, and it's a good one. If the noise is in the RHS, then any set of samples is fine. They can be weighted by any mechanism. (If Expectation anyway. I haven't thought about other risk measures, but it might raise some problems...)

It's implementation could be just
```Julia
struct MonteCarloSampler{N} <: AbstractBackwardPassSampler end
function sample_backward_noise_terms(::MonteCarloSampler{N}, node) where {N}
    return rand(N, node.noise_terms)
end
```

We need the re-normalization in the code above because for cyclic models in SDDP.jl, the `sum(original_probability)` might be strictly `< 1.0`. So we can't re-normalize using `1 / number_of_samples`.

>  I think all of the above holds also if you sample with the properly modified probabilities calculated for the risk measure,

If you use the different probabilities to generate the cuts, your change-of-measure idea is essentially this: https://arxiv.org/abs/1901.01302

Using the different probabilities to sample trajectories on the forward pass is interesting though. We've thought about it, but it's not implemented. It would just be a new `AbstractSamplingScheme`.

**Comment by aferragu** [comment]
> We need the re-normalization in the code above because for cyclic models in SDDP.jl, the sum(original_probability) might be strictly < 1.0. So we can't re-normalize using 1 / number_of_samples.

Sorry, my bad. `original_probability` includes the Markov transitions (`child_probability`). What I've meant is to take `noise.probability = 1/number_of_samples`. Then `original_probability` goes to `child_probability * 1/number_of_samples` and may not sum up to 1 (which is right, I agree).

The final objective would be that when `refine_bellman_function` is called, the `nominal_probability` argument should be `child_probability * 1/number_of_samples` and then the risk adjusted version is performed inside (change of measure) and averaged.

The problem with this approach is that you are messing with noise.probability, which I am still not sure how will affect subsequent iterations, in particular the forward pass simulation.

**Comment by odow** [comment]
Oops. I've realized that I made a mistake in that code (hence us talking past each other). I've edited the post to reflect the change.

> The problem with this approach is that you are messing with noise.probability, which I am still not sure how will affect subsequent iterations, in particular the forward pass simulation.

We should never mess with `noise.probability`. Only the vector that we pass `refine_bellman_function`.

**Comment by aferragu** [comment]
Yeah I agree. `noise.probability` is user provided. So if `original_probability` stores the probabilities that then get passed to `refine_bellman_function`, then one should sample following the contents of `noise.probabilty` but store:
`push!(original_probability, child.probability * 1/number_of_samples)` am I right?

**Comment by odow** [comment]
Good idea. This is much simpler. Don't sample across children, just from the noise terms within a child. It might solve the risk problem as well. If you just have a linear policy graph (guessing this is your case?) then it is what you originally had in mind.

**Comment by aferragu** [comment]
I was thinking both in linear and markov, and it should work. For Markov, you have to keep the `child_probabilty` there obviously.

**Comment by roporte** [comment]
Hi, 

Hello, Im trying to get the last commit of master branch in dev mode but I get an old commit from April 26th (e3dcf54431fe97e8ca6537d724ac69cd2af22c60). How can i get the last commit? I can develop in a local folder and make the dev command there, but I would prefer to do it from the original repository.

Thanks!

**Comment by odow** [comment]
So, the steps are
```Julia
] dev https://github.com/odow/SDDP.jl
```
Okay, so now it should be in `~/.julia/dev/SDDP` for you to edit. Then run
```Julia
] up SDDP
```
to grab the latest commit. If that doesn't work (version conflicts or because you've edited some files), you can use the git command line
```
cd ~/.julia/dev/SDDP
git pull master
```
Then you will want to make a branch
```
git checkout -b roporte/noise
```

**Comment by aferragu** [comment]
Yeah we did that, but somehow it's not working. If we clone the repository by command line git, everything seems ok and the git history is current with the master branch. However, if you ask Julia to clone it via dev to start developing, it somehow leaves the master branch in the last commit before my pull request, and has a lot of "cached" pulls with the latest commits. Everything is in there but the history is messed up. Again, by git clone it works fine so I don't know what's happening....and I don't know if it easy to reproduce elsewhere....

**Comment by odow** [comment]
Hmm. I'm not sure. I always use the command line git, so I don't have any suggestions.

**Comment by rodripor** [comment]
Hi,

I reopened this issue because im trying to implement a Stochastic Decomposition Technique described in Higle and Sen 1996 book "stochastic decomposition". MonteCarlosSampler implemented doesn't guarantee a lower bound because it doesn't cover all possible noises. One of stochastic decomposition techniques guarantees convergence and for that it requires modifying the coefficients of the existing cuts to attenuate them. The question is how i can access existing cuts inside JuMP to modify its coefficientes without having to delete them and generate them again.


Thanks,
Rodrigo
