### ISSUE TITLE
 Can state variable x.in be converted to an input parameter?

### ISSUE THREAD

**Issue by Esnilg** [odow/SDDP.jl#319]
Hi,

I hope you are well.  To explain the problem I have, I take the farmer's problem as an example. In this function you pass the value of `subproblem[:area][c].in` in the second stage as a variable and not as a parameter, right? because the problem that I present is that if the coefficient of this variable is stochastic process, that is, `A_ [1] = at_[1] * A_[0] + noise_[0]`. Then the equation would result in a multiplication of two variables. So to overcome this, can you get the value of `subproblem[:area][c].in` in the second stage?

Best regards
```Julia
function second_stage_uncertainty(subproblem)
    @constraint(subproblem, uncertainty[c=CROPS],
        1.0 * subproblem[:area][c].in == subproblem[:yield][c])
    SDDP.parameterize(subproblem, [:good, :fair, :bad]) do ω
        for c in CROPS
            JuMP.set_normalized_coefficient(
                uncertainty[c],
                subproblem[:area][c].in,
                MEAN_YIELD[c] * YIELD_MULTIPLIER[ω]
            )
        end
    end
end
```

**Comment by odow** [comment]
I don't fully understand the question, so I might be answering a different question, but 

> can you get the value of subproblem[:area][c].in in the second stage?

No. It is a decision variable. This is a design choice to prevent people from constructing non-convex problems. You can have the `.in` state variable appear additively in a constraint or the objective, and you can multiply the `.in` state variable by a random quantity (as we do above), but you cannot multiply the `.in` state variable with another decision variable.

What are `A`, `at` and `noise` in your problem? Where do they appear? There are different ways of working around this problem.

**Comment by Esnilg** [comment]
Dear Oscar

We are trying to do is that in the next stage the calculation of the demand, for example: passenger mobility, is:

D [private, p] = EUI [mobility] .in / 8760 * X.in, with p in 1:12

D [public, p] = EUI [mobility] .in / 8760 * (1 - X.in), with p in 1:12

X.in is a strategic variable between [0.3,0.5] that decides how much to share the mobility between private and public. EUI [mobility]  is an autoregressive process.

Finally :

EUI [mobility] .out = const_t * EUI [mobility] .in + noise[t]

**Comment by odow** [comment]
As currently formulated, this is not a convex problem, so you cannot use SDDP.

If you need to keep the autoregressive process, you approximate it by a discretized Markov chain.

If your process is one-dimensional (e.g., what is mobility), you can use: https://odow.github.io/SDDP.jl/latest/guides/create_a_general_policy_graph/#Creating-a-Markovian-graph-automatically-1

Otherwise, you will have to discretize the process yourself and provide the transition matrices: https://odow.github.io/SDDP.jl/latest/tutorial/04_markov_uncertainty/

Another alternative is to use the McCormick relaxation of the bilinear term between mobility and X. Train with the convexified model. Save the cuts to file. Build a new model, this time with the bilinear term, load the cuts from file, and simulate without training.

**Comment by Esnilg** [comment]
Ok, I will be reading your recommendations, thank you very much
