### ISSUE TITLE
ERROR: SystemError: opening file "SDDP.log": Permission denied

### ISSUE THREAD

**Issue by hssharadga** [odow/SDDP.jl#401]
Hi!

Thanks a lot for sharing your library

I was following the example given in:

https://odow.github.io/SDDP.jl/stable/examples/Hydro_thermal/#Hydro-thermal-scheduling

I got the following message error: ERROR: SystemError: opening file "SDDP.log": Permission denied

The command of " SDDP.train(model, iteration_limit = 100)" in the **Training the policy section** is the source of the issue.

I have another question please: which platform/interface do you use to run Julia? Is it atom, Juno? I have not used Julia before. I am using if for the first time.

**Comment by odow** [comment]
Download Julia from here:
https://julialang.org/downloads/

Use VS-Code:
https://www.julia-vscode.org

**Don't use JuliaPro. It causes more hassles than it is worth.**

The error is because your local directory isn't writeable. Use `cd("/path/to/directory")` at the start of your script to change your current directory, replacing `/path/to/directory` with the correct path.

**Comment by hssharadga** [comment]
Thanks!
