### ISSUE TITLE
Historical ForwardPass sampling scheme

### ISSUE THREAD

**Issue by odow** [odow/SDDP.jl#414]
Write a forward pass sampling scheme that samples from historical data with some probability.

**Comment by adow031** [comment]
Historical sampling schemes have already been implemented (see below from line ~300 of `sampling_schemes.jl`). However, we're interested in sequential sampling, rather than random sampling. Is this possible to do this?

The only way I could think to do it would be to replace the `sample_scenario` or `sample_noise` functions, but there doesn't appear to be native support for this.

```
function Historical(
    scenarios::Vector{Vector{Tuple{T,S}}},
    probability::Vector{Float64} = fill(1.0 / length(scenarios), length(scenarios)),
) where {T,S}
    if sum(probability) != 1.0
        error(
            "Probability of historical scenarios must sum to 1. Currently: " *
            "$(sum(probability)).",
        )
    end
    output = Noise{Vector{Tuple{T,S}}}[]
    for (scenario, prob) in zip(scenarios, probability)
        push!(output, Noise(scenario, prob))
    end
    return Historical(output)
end
```

**Comment by odow** [comment]
Yeah I can add this. We just increment a counter inside the object.

Looping through probably makes more sense than random regardless.

**Comment by adow031** [comment]
Thanks for implementing this so quickly.
