### ISSUE TITLE
Add better documentation on relatively complete recourse

### ISSUE THREAD

**Issue by odow** [odow/SDDP.jl#436]
https://github.com/odow/SDDP.jl/issues/435#issuecomment-872110680

Something like
````
## Relatively complete recourse

Models built in SDDP.jl need a property called _relatively complete recourse_.

One definition of relatively complete recourse is that _all_ feasible decisions
(not necessarily optimal) in a subproblem lead to feasible decisions in future 
subproblems.

For example, in the following problem, one feasible first stage decision is 
`x.out = 0`. But this causes an infeasibility in the second stage which requires 
`x.in >= 1`. This will throw an error about infeasibility if you try to solve.
```julia
SDDP.LinearPolicyGraph(stages = 2, lower_bound = 0) sp, t
    @variable(sp, x >= 0, SDDP.State, initial_value = 1)
    if t == 2
        @constraint(sp, x.in >= 1)
    end
    @stageobjective(sp, x.out)
end
```

!!! warning
    The actual constraints causing the infeasibilities can be deceptive! A good
    strategy to debug is to comment out all constraints. Then, one-by-one, 
    uncomment the constraints and try resolving the model to check if it finds a
    feasible solution.
````

**Comment by BYS-NCEPU** [comment]
thank you,@Oscar, I understand the meaning, i think it maybe just the problem. Because I have relax all feasible constraints, which only remain the discrete constraints(logical constraints). Just like you say, every stage aims at minimize the objective function, so x.out of the first stage above is 0, it will conflict with x.in of the second stage.

**Comment by odow** [comment]
If you have integrality, then we solve the LP problem in the backward pass when generating cuts. Therefore, we need all _fractional_ solutions to also have this property. Without seeing your model, it's impossible to say more, however.

If you can simplify the problem down to a (very) minimal example, I may be able to help. Otherwise, good luck.

**Comment by BYS-NCEPU** [comment]
@odow ,thank you, again. I guess the model can not be simplified easily because i just cannot determine which part leads to the infeasibility,  however, it is more convenient if I can send my model by e-mail and communicate by e-mail(some codes may not want to be public for the time being, but for future).
