### ISSUE TITLE
GARCH?

### ISSUE THREAD

**Issue by bernardokp** [odow/SDDP.jl#504]
Hello Oscar,

here am I again, to make your life miserable. So, do you have a GARCH module at sddp.jl? 
Those guys suggest it can be readily implemented within sddp:

http://www.optimization-online.org/DB_FILE/2019/05/7199.pdf

What do you say? As a nudge, people in economics love GARCH, it could be a nice feature to be added. 
How complicated is it to implement it?

Best,
Bernardo

**Comment by odow** [comment]
No, there is no explicit GARCH functionality. You'd need to manually formulate it. You need to add the lag terms as state-variables, and then write the transition function for the GARCH process as a constraint. This means you're a little restricted in where you can use the resulting term; it probably has to appear additively in a constraint or objective, rather than as a multiplicative coefficient (i.e., as a price).

Closing in favor of https://github.com/odow/SDDP.jl/issues/443. I'll add it to the list of "document it at some point."
