### ISSUE TITLE
Rename ':noise' key in solution storage

### ISSUE THREAD

**Issue by vitorlppf** [odow/SDDP.jl#84]
Greetings,

I'm working on an out-of-sample simulation function based on the existing 'simulate' functions. Currently it receives a list of SDDP.Noise objects (of size equal to the number of stages). I created methods to save the results, including the values of the SDDP.Noise argument in a key temporarily named ':new_noise'.

I think the name ':noise' for the storage key that represents the index for the noise in the model is unclear. Especially if you intend to implement sampling oracles as per #80. I'd like to suggest renaming the ':noise' key to ':noiseidx' or similar. What's your opinion on this?

Thanks,
Vitor.

**Comment by odow** [comment]
Hey Vitor, implementing an out of sample simulator sounds great! 

One issue is that renaming the key would break a lot of existing code. 

I'd be more in favour a bigger reorganisation that included returning the actual noise object (or implementing the oracles since they seem the next most important thing).

**Comment by vitorlppf** [comment]
I renamed the keys in my local branch, and it broke my own code! It was a trivial fix, but I can see how it would disrupt other people's code. I believe a way of implementing this change without such issues would be creating a new `simulate` method, and deprecating the existing ones.

I think having `0` indicate when `:noiseidx` is sensible, because the output would still always be a (non-negative) `Int`. It's easy to program around too. I was thinking about `:noise` being an array with the noise values, but associating it with [`Noise`](https://github.com/odow/SDDP.jl/blob/master/src/typedefinitions.jl#L63-L70) objects sounds like a better idea.

I could implement the key name changes and `SamplingOracles` (#80) as well, if you haven't worked on it already. Since you probably already gave it some thought, is there any particular detail you have in mind for them?

**Comment by odow** [comment]
I haven't worked on them. They would be a great contribution!

The only thoughts I've had I put down in #80. They seem like a good starting point.

I think once we have sampling oracles, figuring out a new (improved) simulation method will be easier.

> I was thinking about :noise being an array with the noise values

This gets a little tricky because I often go
```julia
w = [1, 2, 4]
@rhsnoise(sp, i=1:3, x <= w[i])
```
Should the noise values be `1,2,3` or `1,2,4`?

I would suggest making a Pull Request that begins to implement sampling oracles, and we can continue the discussion there. I'm sure we will run into a few problems.
